version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd client && npm install && cd ..
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - cd client && npm run build && cd ..
      - mv client/dist server/dist
artifacts:
  files:
    - server/**
    - Procfile
    - .ebextensions/**
