version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.10.0
    commands:
      - npm install
  build:
    commands:
      - echo "No build step needed for Node.js backend"
  post_build:
    commands:
      - echo "Creating deployment package..."
        - rm -rf node_modules/.bin
        - rm -rf node_modules/*/test
        - rm -rf node_modules/*/tests
        - rm -rf node_modules/*/docs
        - rm -rf node_modules/*/examples
artifacts:
  files:
    - "**/*"
  base-directory: "."
